# Generated by Django 3.2.25 on 2024-07-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='smdp_email',
            new_name='smtp_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='smdp_password',
            new_name='smtp_password',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
