# Generated by Django 3.2.25 on 2024-07-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classorganization',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='ClassOrganization',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
